# Arquivo de configuração da extenção prettier 

printWidth = 80

tabWidth = 2 

useTabs = false

semi = true

singleQuote = false

quoteProps = "consistent"

trailingComma = "all"

bracketSpacing = true

bracketSameLine = true

arrowParens = "always"

requirePragma = false

insertPragma = true

proseWrap = "preserve"

htmlWhitespaceSensitivity = "ignore"

endOfLine = "lf"

embeddedLanguageFormatting = "auto"

singleAttributePerLine = true